"""fix_score_column_precision

Revision ID: 08b386e2f302
Revises: a579f5313356
Create Date: 2026-03-11 00:25:29.834236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b386e2f302'
down_revision: Union[str, None] = 'a579f5313356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_risk_scores', 'credit_utilization_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('customer_risk_scores', 'terms_adherence_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('customer_risk_scores', 'delinquency_severity_idx',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('customer_risk_scores', 'weighted_avg_daysoverdue',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_risk_scores', 'weighted_avg_daysoverdue',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('customer_risk_scores', 'delinquency_severity_idx',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_risk_scores', 'terms_adherence_ratio',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('customer_risk_scores', 'credit_utilization_ratio',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
