"""add_rendered_email_to_dunning_log

Revision ID: 10eab5164c86
Revises: eb098f724ce5
Create Date: 2026-03-11 22:58:51.507150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10eab5164c86'
down_revision: Union[str, None] = 'eb098f724ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dunning_log', sa.Column('rendered_subject', sa.Text(), nullable=True))
    op.add_column('dunning_log', sa.Column('rendered_body', sa.Text(), nullable=True))
    op.add_column('email_config', sa.Column('signature_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'signature_html')
    op.drop_column('dunning_log', 'rendered_body')
    op.drop_column('dunning_log', 'rendered_subject')
    # ### end Alembic commands ###
