"""m14_schema_extensions

Revision ID: 7f97e233a43d
Revises: 10eab5164c86
Create Date: 2026-03-13 00:18:15.624188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f97e233a43d'
down_revision: Union[str, None] = '10eab5164c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_settings', 'setting_key',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('app_settings_setting_key_key', 'app_settings', type_='unique')
    op.drop_column('app_settings', 'setting_id')
    op.create_foreign_key(None, 'dunning_worklist', 'customers', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'dunning_worklist', 'invoices', ['invoice_id'], ['invoice_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dunning_worklist', type_='foreignkey')
    op.drop_constraint(None, 'dunning_worklist', type_='foreignkey')
    op.add_column('app_settings', sa.Column('setting_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('app_settings_setting_key_key', 'app_settings', ['setting_key'])
    op.alter_column('app_settings', 'setting_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
