"""v2_currency_email_mapping_dunning_updates

Revision ID: 83485925ae64
Revises: 08b386e2f302
Create Date: 2026-03-11 10:44:26.322902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83485925ae64'
down_revision: Union[str, None] = '08b386e2f302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('rate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rate_id')
    )
    op.create_table('email_config',
    sa.Column('email_config_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.SmallInteger(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('default_to', sa.Text(), nullable=True),
    sa.Column('default_cc', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('reporting_currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email_config_id')
    )
    op.create_table('import_field_mapping',
    sa.Column('mapping_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mapping_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('source_field', sa.String(length=255), nullable=True),
    sa.Column('target_field', sa.String(length=100), nullable=True),
    sa.Column('transform_rule', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.add_column('dunning_config_steps', sa.Column('ladder_key', sa.String(length=100), nullable=True))
    op.add_column('dunning_config_steps', sa.Column('template_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_constraint('uq_config_step', 'dunning_config_steps', type_='unique')
    op.create_unique_constraint('uq_config_ladder_step', 'dunning_config_steps', ['config_id', 'ladder_key', 'step_number'])
    op.create_foreign_key(None, 'dunning_config_steps', 'dunning_templates', ['template_id'], ['template_id'])
    op.add_column('dunning_log', sa.Column('sent_cc', sa.Text(), nullable=True))
    op.alter_column('dunning_log', 'sent_to',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('invoices', sa.Column('reporting_currency', sa.String(length=10), nullable=True))
    op.add_column('invoices', sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('invoices', sa.Column('exchange_rate_source', sa.String(length=20), nullable=True))
    op.add_column('scoring_config', sa.Column('ladder_assignment_mode', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scoring_config', 'ladder_assignment_mode')
    op.drop_column('invoices', 'exchange_rate_source')
    op.drop_column('invoices', 'exchange_rate')
    op.drop_column('invoices', 'reporting_currency')
    op.alter_column('dunning_log', 'sent_to',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('dunning_log', 'sent_cc')
    op.drop_constraint(None, 'dunning_config_steps', type_='foreignkey')
    op.drop_constraint('uq_config_ladder_step', 'dunning_config_steps', type_='unique')
    op.create_unique_constraint('uq_config_step', 'dunning_config_steps', ['config_id', 'step_number'])
    op.drop_column('dunning_config_steps', 'template_id')
    op.drop_column('dunning_config_steps', 'ladder_key')
    op.drop_table('import_field_mapping')
    op.drop_table('email_config')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
