"""initial_schema

Revision ID: a579f5313356
Revises: 
Create Date: 2026-03-11 00:07:59.447444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a579f5313356'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_config',
    sa.Column('ai_config_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_path', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('llama_cpp_port', sa.Integer(), nullable=True),
    sa.Column('llama_cpp_host', sa.String(length=100), nullable=True),
    sa.Column('gpu_layers', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ai_config_id')
    )
    op.create_table('api_keys',
    sa.Column('api_key_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rate_limit_per_min', sa.SmallInteger(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('api_key_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('customer_category', sa.String(length=50), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_limit_updated_at', sa.DateTime(), nullable=True),
    sa.Column('dnb_paydex_score', sa.SmallInteger(), nullable=True),
    sa.Column('dnb_score_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_table('data_import_log',
    sa.Column('import_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('success_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_by', sa.String(length=100), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('import_id')
    )
    op.create_table('dunning_templates',
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('dunning_step', sa.SmallInteger(), nullable=True),
    sa.Column('customer_category', sa.String(length=50), nullable=True),
    sa.Column('subject_line', sa.Text(), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('erp_connections',
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('erp_type', sa.String(length=50), nullable=True),
    sa.Column('integration_mode', sa.String(length=20), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.String(length=20), nullable=True),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_frequency_mins', sa.SmallInteger(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('scoring_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('weight_dsi', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weight_tar', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weight_ispv', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weight_cur', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weight_crh', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weight_3pc', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weight_dnb', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('dnb_decay_months', sa.SmallInteger(), nullable=True),
    sa.Column('threepc_decay_months', sa.SmallInteger(), nullable=True),
    sa.Column('default_new_customer_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_invoice_threshold', sa.SmallInteger(), nullable=True),
    sa.Column('crh_rolling_months', sa.SmallInteger(), nullable=True),
    sa.Column('band_green_floor', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('band_amber_floor', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('band_red_floor', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dunning_day1', sa.SmallInteger(), nullable=True),
    sa.Column('dunning_day2', sa.SmallInteger(), nullable=True),
    sa.Column('dunning_day3', sa.SmallInteger(), nullable=True),
    sa.Column('dunning_day4', sa.SmallInteger(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('customer_risk_scores',
    sa.Column('score_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('behavioral_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('anchor_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('business_adjusted_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('risk_band', sa.String(length=20), nullable=True),
    sa.Column('credit_utilization_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('terms_adherence_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('delinquency_severity_idx', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weighted_avg_daysoverdue', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('open_ar_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('score_trigger', sa.String(length=50), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_version'], ['scoring_config.config_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_table('dunning_config_steps',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.SmallInteger(), nullable=False),
    sa.Column('trigger_offset', sa.SmallInteger(), nullable=False),
    sa.Column('step_label', sa.String(length=100), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=True),
    sa.Column('penalty_weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['scoring_config.config_id'], ),
    sa.PrimaryKeyConstraint('step_id'),
    sa.UniqueConstraint('config_id', 'step_number', name='uq_config_step')
    )
    op.create_table('erp_sync_log',
    sa.Column('sync_log_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sync_mode', sa.String(length=20), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['erp_connections.connection_id'], ),
    sa.PrimaryKeyConstraint('sync_log_id')
    )
    op.create_table('field_mapping_config',
    sa.Column('mapping_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('erp_entity', sa.String(length=100), nullable=True),
    sa.Column('erp_field', sa.String(length=100), nullable=True),
    sa.Column('credit_tool_table', sa.String(length=100), nullable=True),
    sa.Column('credit_tool_field', sa.String(length=100), nullable=True),
    sa.Column('transform_rule', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['erp_connections.connection_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('dispute_flag', sa.Boolean(), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('collections_history',
    sa.Column('collection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_by', sa.String(length=100), nullable=True),
    sa.Column('amount_at_risk', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_recovered', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('recovery_date', sa.Date(), nullable=True),
    sa.Column('sent_to_3p', sa.Boolean(), nullable=True),
    sa.Column('third_party_agency', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('dunning_log',
    sa.Column('dunning_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dunning_step', sa.SmallInteger(), nullable=True),
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_via', sa.String(length=30), nullable=True),
    sa.Column('sent_to', sa.String(length=255), nullable=True),
    sa.Column('delivery_status', sa.String(length=30), nullable=True),
    sa.Column('days_past_due_at_send', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['dunning_templates.template_id'], ),
    sa.PrimaryKeyConstraint('dunning_id')
    )
    op.create_table('invoice_risk_flags',
    sa.Column('flag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=True),
    sa.Column('flag_severity', sa.String(length=20), nullable=True),
    sa.Column('flag_message', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('days_to_pay', sa.Integer(), nullable=True),
    sa.Column('days_past_due', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('invoice_risk_flags')
    op.drop_table('dunning_log')
    op.drop_table('collections_history')
    op.drop_table('invoices')
    op.drop_table('field_mapping_config')
    op.drop_table('erp_sync_log')
    op.drop_table('dunning_config_steps')
    op.drop_table('customer_risk_scores')
    op.drop_table('scoring_config')
    op.drop_table('erp_connections')
    op.drop_table('dunning_templates')
    op.drop_table('data_import_log')
    op.drop_table('customers')
    op.drop_table('api_keys')
    op.drop_table('ai_config')
    # ### end Alembic commands ###
